#!/bin/bash
# Run this AFTER deploying to Netlify
# Pings Google to re-crawl your sitemap

echo "🔍 Pinging Google with updated sitemap..."
curl -s "https://www.google.com/ping?sitemap=https://newparentreviews.com/sitemap.xml"
echo ""
echo "✅ Sitemap ping sent!"
echo ""
echo "📋 NOW DO THIS MANUALLY (takes 5 min):"
echo "1. Go to https://search.google.com/search-console"
echo "2. Select newparentreviews.com"
echo "3. Click 'URL Inspection' in sidebar"
echo "4. Paste EACH of these URLs and click 'Request Indexing':"
echo ""
echo "   TOOLS (priority — these are your traffic magnets):"
echo "   https://newparentreviews.com/tools/baby-fever-checker"
echo "   https://newparentreviews.com/tools/congestion-checker"
echo "   https://newparentreviews.com/tools/feeding-calculator"
echo "   https://newparentreviews.com/tools/baby-sleep-schedule"
echo "   https://newparentreviews.com/tools/growth-percentile-calculator"
echo "   https://newparentreviews.com/tools/diaper-rash-checker"
echo "   https://newparentreviews.com/tools/"
echo ""
echo "   PRODUCTS (secondary):"
echo "   https://newparentreviews.com/products/grownsy-nasal-aspirator"
echo "   https://newparentreviews.com/products/baby-monitor-review"
echo "   https://newparentreviews.com/products/papablic-bottle-sterilizer"
echo "   https://newparentreviews.com/products/halo-bassinest-swivel-sleeper-review"
echo "   https://newparentreviews.com/products/frida-baby-thermometer"
echo ""
echo "   HOMEPAGE:"
echo "   https://newparentreviews.com/"
echo ""
echo "5. Also go to Sitemaps → resubmit: sitemap.xml"
echo ""
echo "⏰ Google typically re-indexes within 2-7 days after this."
